[feat] #4 통계 페이지 퍼블리싱
LawDigest/LawDigest-FE pull request #5
Opened 2023-12-05 05:15 UTC by ijaesin

## 1. 무슨 이유로 코드를 변경했나요?
- #4 
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
- 바텀 네비게이션이 페이지 중간 영역을 침법하여 고정 돼있습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.
<img width="379" alt="image" src="https://github.com/LawDigest/LawDigest-FE/assets/80256934/b0ecc6de-207c-4769-a0ca-eb261694f4ad">
<img width="379" alt="image" src="https://github.com/LawDigest/LawDigest-FE/assets/80256934/953993f4-5cb7-4a82-a5e3-37ba7a38ea22">

<br>

## 4. 완료 사항
- [x] 최근 법안 발의한 정당
- [x] 21대 국회 의석수 현황
- [x] 최근 법안 발의한 의원
- [x] 6월 국회 주요 키워드
<br>

## 5. 추가 사항
- 최근 법안 발의한 정당 가로 스크롤 구현할 예정입니다.
- 최근 법안 발의한 의원, 6월 국회 주요 키워드 카드에 목업 이미지들은 추후에 코드로 교체할 예정입니다.

2023-12-05 07:07 UTC, Collection50 requested changes

2023-12-05 07:07 UTC, Collection50 commented on app/layout.tsx
> +            <main className="flex items-center justify-center w-full h-full">
CSS 순서를 바꾸신 이유가 있나요?

2023-12-05 07:07 UTC, Collection50 commented on app/layout.tsx
> +                <div className="w-full min-h-content">{children}</div>
이 div 태그의 의미가 궁금합니다 !
`min-h-content`는 무엇을 의미하나요 ??

2023-12-05 07:07 UTC, Collection50 commented on app/statistics/components/CardItem.tsx
> +}
`interface`, `type` 중 `interface`를 사용하신 이유가 있나요??

2023-12-05 07:07 UTC, Collection50 commented on app/statistics/components/member/MemberList.tsx
> +              .map((member) => (
```suggestion
              .map(({ name, profileImg, partyImg, number }) => (
```

위와 같이 사용하면 더 좋을 것 같아요.

2023-12-05 07:07 UTC, Collection50 commented on app/statistics/components/member/MemberList.tsx
> +            ))}
코드가 중복되는 것 같아서 길어지는 느낌인데 위에서 처리해주는 건 어떻게 생각하시나요?

2023-12-05 07:07 UTC, Collection50 commented on app/statistics/components/party/PartyContainer.tsx
> +      {list.map((party) => (
위의 구조분해 할당 리뷰와 같습니다 :)

2023-12-05 07:07 UTC, Collection50 commented on app/statistics/components/CardItem.tsx
> +export default function CardItem({ title, children }: CardItemProps) {
`next-ui`의 `Card`를 사용하시지 않은 이유가 있나요?

2023-12-05 07:07 UTC, Collection50 commented on app/statistics/components/member/MemberList.tsx
> +    profileImg: '/mock/사용자_프로필.svg',
`profileImg`는 사진이 아니라 `next-ui`의 `Avatar`, `User`를 사용하는게 좋을 것 같습니다 :)

2023-12-05 07:14 UTC, ijaesin commented on app/layout.tsx
> +                <div className="w-full min-h-content">{children}</div>
module.exports = {
  ...
  theme: {
    minHeight: {
      content: 'calc(100vh - 117px)',
    },
    extend: {},
  },
  ...
};

tailwind.config.js 에서 규정한 칠드런 컴포넌트 크기입니다. 근데 children height 길이가 길어지면서 페이지 한가운데 바텀 네비게이션이 위치하는 오류가 생겨서 이 부분은 수정할 예정입니다.

2023-12-05 07:14 UTC, ijaesin commented on app/statistics/components/CardItem.tsx
> +}
type보다 interface가 범용성이 넓어서 저는 개발할 때 interface로 통일해서 사용합니다.

2023-12-05 07:15 UTC, ijaesin commented on app/statistics/components/CardItem.tsx
> +export default function CardItem({ title, children }: CardItemProps) {
npm 관련 문제가 생기는데 해결하려다 시간이 좀 걸려서 일단 자체로 만든 컴포넌트를 사용했어요.

2023-12-05 07:16 UTC, ijaesin commented on app/statistics/components/member/MemberList.tsx
> +    profileImg: '/mock/사용자_프로필.svg',
위와 마찬가지로 npm 문제가 생겨서 자체적으로 사용했습니다.

2023-12-05 15:57 UTC, ijaesin commented on app/statistics/components/CardItem.tsx
> +export default function CardItem({ title, children }: CardItemProps) {
추후에 인터페이스 업그레이드와 동시에 교체하겠습니다.

2023-12-05 15:57 UTC, ijaesin commented on app/statistics/components/member/MemberList.tsx
> +    profileImg: '/mock/사용자_프로필.svg',
추후에 인터페이스 업그레이드와 동시에 교체하겠습니다.

2023-12-06 03:59 UTC, Collection50 approved these changes

2023-12-06 04:14 UTC, merged